### ISSUE TITLE
Make Hyper-V optional

### ISSUE THREAD

**Issue by slonopotamus** [slonopotamus/stevedore#17]
In e82e4a02d565f3d6af781f9765762ae2ad99bc4a, we started installing Hyper-V feature unconditionally.

However, on Windows Server, it may not be desirable to install Hyper-V and only use container isolation.

**Comment by slonopotamus** [comment]
@Hvid You can try msi from https://github.com/slonopotamus/stevedore/actions/runs/1677207268. Is that OK for your needs?

**Comment by Hvid** [comment]
Thanks, it works perfect.

I'm getting Docker CE. Never tried that on a server before. Do you know if this is an issue? I seem to remember only EE being supported on Windows Server.

**Comment by slonopotamus** [comment]
CE/EE is just marketing/support thing. Technically, they are absolutely identical.

**Comment by Hvid** [comment]
Awesome, thanks! Will it be possible to set this option on a chocolatey install as well?

**Comment by slonopotamus** [comment]
Hopefully, [this](https://github.com/slonopotamus/stevedore#command-line-install-options) fully answers your question.

In the future, I suggest creating separate GitHub issues for unrelated topics.
