### ISSUE TITLE
Possible to customize service name?

### ISSUE THREAD

**Issue by Hvid** [slonopotamus/stevedore#18]
Can you make it possible to customize the windows service name?

**Comment by slonopotamus** [comment]
In theory, yes, it is possible. Note that I deliberately avoided `docker` service name because that [conflicts with DockerMsftProvider](https://github.com/OneGet/MicrosoftDockerProvider/blob/v1.0.0.1/DockerMsftProvider.psm1#L41).

**Comment by Hvid** [comment]
I want to use stevedore on new servers instead of DockerMsftProvider, but would like a smooth transition regarding monitoring

**Comment by Hvid** [comment]
Beautiful, thank you. I'll be using the chocolatey package :)

**Comment by Hvid** [comment]
Can you please publish this change to chocolatey?

**Comment by slonopotamus** [comment]
Sure: https://community.chocolatey.org/packages/stevedore/0.0.5

**Comment by Hvid** [comment]
Thanks :)

**Comment by slonopotamus** [comment]
@Hvid I suspect that Stevedore [docs](https://github.com/slonopotamus/stevedore#advanced-command-line-install-options) on passing custom MSI options are a bit wrong. Could you please share how you customize service name? I'm personally not very MSI-savvy :D

**Comment by Hvid** [comment]
I'm installing it this way:
`"C:\Windows\System32\msiexec.exe" /i "C:\Users\Administrator\AppData\Local\Temp\5\chocolatey\stevedore\0.6.0\stevedore-0.6.0-x86_64.msi" /qn /norestart /l*v "C:\Users\Administrator\AppData\Local\Temp\5\chocolatey\stevedore.0.6.0.MsiInstall.log" INSTALLDIR="C:\Program Files\Docker" ADDLOCAL=FeatureWindowsContainers SERVICENAME=docker /quiet`

**Comment by slonopotamus** [comment]
Thanks, adjusted docs
