### ISSUE TITLE
docker-credential-desktop issue

### ISSUE THREAD

**Issue by blachawk** [slonopotamus/stevedore#20]
### Version

0.0.4

### What steps are needed to reproduce the behavior?

* I uninstalled my previous version of Docker Destkop in Windows 10. But this did not completely remove the .docker configurations set in my Windows 10 system.
* I then installed stevedore and restarted my windows 10 machine
* I went into an existing docker directory on my computer, which has an already tested and working docker-compose.yml file.
* From my workspace terminal, I type in `docker compose up -d` to run it, but my bash terminal responded with the following error

```bash
$ docker compose up -d
[+] Running 0/0
 - phpmyadmin Pulling                                                                                                                                                               0.1s 
 - db Pulling                                                                                                                                                                       0.1s 
error getting credentials - err: exec: "docker-credential-desktop": executable file not found in %PATH%, out: ``
```

What should I do?

### What you expected?

I expected my docker compose command to fully work like it did prior with Docker Desktop for Windows

### What happened?

It stopped and threw an error

**Comment by slonopotamus** [comment]
I think you need to remove `C:\Users\<your username>\.docker\config.json`. That file still has some leftover configuration from Docker Desktop, that no longer works because executables were removed when yoou uninstalled Docker Desktop.
