### ISSUE TITLE
On fresh Windows install, launch fails due to missing msvcp140.dll

### ISSUE THREAD

**Issue by intersectRaven** [slonopotamus/stevedore#35]
### Version

0.3.3

### What steps are needed to reproduce the behavior?

1. Have fresh Windows install.
2. Install Stevedore.
3. Restart to complete installation.
4. Stevedore startup launch fails. If you try and launch manually, you'll be prompted by the missing dll.

### What you expected?

Stevedore launches on startup.

### What happened?

Missing msvcp140.dll.

### Additional context

Although I doubt anyone will be installing this on a fresh windows install, it doesn't hurt to cover all launch prerequisites in order foro the executable to function.

**Comment by slonopotamus** [comment]
This issue was fixed in just-released Stevedore 0.3.4
