### ISSUE TITLE
Can't connect to a container using machine private IP or host.docker.internal

### ISSUE THREAD

**Issue by rho-cassiopeiae** [slonopotamus/stevedore#43]
### Version

0.6.0

### What steps are needed to reproduce the behavior?

1) Start a container with a port exposed.
2) Connect to it using "localhost" – works.
3) Connect using "host.docker.internal" or host machine private IP – doesn't work. Connection refused.

### What you expected?

Connecting successfully.

### What happened?

Connection refused.

Also, may be related or not: after installing Stevedore, Docker Desktop no longer has bridge network plugin installed, so it fails to create any networks. I don't run Stevedore and Docker Desktop at the same time. After uninstalling Stevedore, the plugin magically reappears and DD starts working properly again.

**Comment by slonopotamus** [comment]
First, WRT `host.docker.internal`: I believe it has a different purpose. It is used to connect *from container* to host. While Stevedore doesn't automagically write `/etc/hosts` entry for it, you can use `--add-host=host.docker.internal:host-gateway` to add it. See https://github.com/moby/moby/pull/40007, this is a standard Docker feature.

As for connecting *to container* using host IP - I need to do some investigation, no comments here yet.

**Comment by rho-cassiopeiae** [comment]
yeah, I know. I use host.docker.internal in my connection strings to postgres, elastic, etc., because I often launch my app as a container in the same network, but sometimes I launch it outside of docker. When I launch it alongside other containers I should use service names instead of IP addresses, and when I launch it as a standalone app I should use localhost. But I don't like having multiple config files for local dev or change values all the time, so I use host.docker.internal instead. It works for both cases, because it's just an alias for private IP.

And while Stevedore doesn't write to hosts, DD does, so I already have host.docker.internal resolving to the host's private IP. When it fails to connect there is an error saying that connection to my private IP (not host.docker.internal) refused. So it resolves just fine.

**Comment by joeri-jansen** [comment]
Perhaps this is related to how WSL works? It does not expose the ports on your LAN adapter by default, however, you can make explicit mappings:
https://docs.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan

**Comment by slonopotamus** [comment]
Stevedore is no longer providing support for Linux containers. See [why](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone). I recommend switching to [Rancher Desktop](https://rancherdesktop.io/), [Container Desktop](https://container-desktop.io/) or [Colima](https://github.com/abiosoft/colima).
