### ISSUE TITLE
Docker does not download images via proxy

### ISSUE THREAD

**Issue by altxt** [slonopotamus/stevedore#45]
### Version

0.6.1

### What steps are needed to reproduce the behavior?

I try to run docker in a network where Internet is only accessible via proxy.
Docker, however, seems to ignore the proxy and tries to connect directly, which is not possible in this environment. So it fails with a timeout.
I am running all of the following commands inside `wsl -d stevedore`, even though eventually I need this to work from Windows.

### What you expected?

An image is downloaded successfully from docker hub.

### What happened?

```
hostname:~# docker pull nginx
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp 52.200.78.26:443: i/o timeout
```
or
```
hostname:~# docker pull nginx
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

### Additional context

 I have the following environment variables set
```
hostname:~# env | grep -i proxy
HTTPS_PROXY=http://user:pass@my.proxy:port
HTTP_PROXY=http://user:pass@my.proxy:port
http_proxy=http://user:pass@my.proxy:port
https_proxy=http://user:pass@my.proxy:port
```
Also, a custom root CA certificate is available in `/etc/ssl/certs/`

This is enought for `apk` and `curl` to work:
```
hostname:~# curl https://registry-1.docker.io/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
```

**Comment by sergbolshakov** [comment]
I have the same problem on a Windows 10 machine on a domain network and proxy when trying to download any image.
```
error pulling image configuration: download failed after attempts=6: dial tcp 104.18.123.25:443: i/o timeout
```

**Comment by slonopotamus** [comment]
Stevedore is no longer providing support for Linux containers. See [why](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone). I recommend switching to [Rancher Desktop](https://rancherdesktop.io/), [Container Desktop](https://container-desktop.io/) or [Colima](https://github.com/abiosoft/colima).
