### ISSUE TITLE
Work with maven plugin

### ISSUE THREAD

**Issue by SmallAd** [slonopotamus/stevedore#46]
### Version

0.6.1

### What steps are needed to reproduce the behavior?

I tried to build docker image for java project with dockerfile-maven-plugin.

### What you expected?

build docker image

### What happened?

Receive error that cannot connect to localhost:2375

### Additional context

By default dockerfile-maven-plugin try to connect to localhost:2375. We can configure it using env variable DOCKER_HOST. Could you please clarify what value it should be?

**Comment by slonopotamus** [comment]
1. [dockerfile-maven-plugin](https://github.com/spotify/dockerfile-maven#status-mature) is abandoned for 3 years already
2. Stevedore currently doesn't have an option to expose TCP port. Note that even though Docker Desktop has such option.
3. I don't know whether `dockerfile-maven-plugin` can talk to Windows named pipes. If it can, you should be able to connect via [`//./pipe/dockerDesktopLinuxEngine`](https://github.com/slonopotamus/stevedore/blob/0.6.1/src/main.rs#L57)

**Comment by slonopotamus** [comment]
Stevedore is no longer providing support for Linux containers. See [why](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone). I recommend switching to [Rancher Desktop](https://rancherdesktop.io/), [Container Desktop](https://container-desktop.io/) or [Colima](https://github.com/abiosoft/colima).
