### ISSUE TITLE
After follow the instruciton and installing everything in windows server 2019 version 1809 it doenst appear the icon and i cannot do anything

### ISSUE THREAD

**Issue by gcontrerasj** [slonopotamus/stevedore#47]
### Version

0.6.1

### What steps are needed to reproduce the behavior?

1.Install in windows server 2019 version 1809
2. follow instructions to install stevedore
3. 

### What you expected?

see the symbol to start the docker

### What happened?

doesn't appear anything

**Comment by slonopotamus** [comment]
Quoting [README](https://github.com/slonopotamus/stevedore#supported-oses):

> Windows Server 2016, 2019, 2022 (note that Linux containers are only supported via LCOW due to lack of WSL2)

Tray icon is only used for WSL2. LCOW is handled by system `stevedore` service. Just try `docker run ubuntu`.

Also note that LCOW has _some_ issues and was dropped from Moby upstream.

**Comment by zx900930** [comment]
same with windows server 2022

```
PS C:\Users\user\docker> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.16.1
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 20348 (20348.1.amd64fre.fe_release.210507-1500)
 Operating System: Windows Server 2022 Datacenter Version 2009 (OS Build 20348.707)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.86GiB
 Name: xxxxxx
 ID: xxxxxx
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

And windows server 2022 dropped the wsl2 support.

```
docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v //c/Users/user/docker/docker.sock:/var/run/docker.sock -v portainer_data:/data  portainer/portainer-ce:latest
docker: Error response from daemon: invalid volume specification: '//c/Users/user/docker/docker.sock:/var/run/docker.sock'.
```

**Comment by slonopotamus** [comment]
Stevedore is no longer providing support for Linux containers. See [why](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone). I recommend switching to [Rancher Desktop](https://rancherdesktop.io/), [Container Desktop](https://container-desktop.io/) or [Colima](https://github.com/abiosoft/colima).
