### ISSUE TITLE
ext4.vhdx shrinking?

### ISSUE THREAD

**Issue by olologin** [slonopotamus/stevedore#49]
Hi everyone.
This project is really great! I am using it with pleasure, thanks for your work.

I would like to propose new feature: Is it possible to add small button to the tray menu to compacts ext4.vhdx when user decides to click on it?
Because WSL2 likes to grow its vhdx file, but it doesn't automatically shrink it back.
More details here: https://superuser.com/questions/1606213/how-do-i-get-back-unused-disk-space-from-ubuntu-on-wsl2

Maybe I am not the only one who thinks it might be a good idea.

**Comment by slonopotamus** [comment]
Stevedore is no longer providing support for Linux containers. See [why](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone). I recommend switching to [Rancher Desktop](https://rancherdesktop.io/), [Container Desktop](https://container-desktop.io/) or [Colima](https://github.com/abiosoft/colima).
