### ISSUE TITLE
gpu support?

### ISSUE THREAD

**Issue by MiXaiLL76** [slonopotamus/stevedore#50]
how can i use gpu in these docker? Everything else works great

**Comment by slonopotamus** [comment]
Stevedore is no longer providing support for Linux containers. See [why](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone). I recommend switching to [Rancher Desktop](https://rancherdesktop.io/), [Container Desktop](https://container-desktop.io/) or [Colima](https://github.com/abiosoft/colima).
