### ISSUE TITLE
Support WSL2 on Windows Server

### ISSUE THREAD

**Issue by Hvid** [slonopotamus/stevedore#51]
Microsoft has added support for WSL2 in Windows Server 2022: https://techcommunity.microsoft.com/t5/itops-talk-blog/wsl2-now-available-on-windows-server-2022/ba-p/3447570

Stevedore should support this.

**Comment by slonopotamus** [comment]
Stevedore is no longer providing support for Linux containers. See [why](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone). I recommend switching to [Rancher Desktop](https://rancherdesktop.io/), [Container Desktop](https://container-desktop.io/) or [Colima](https://github.com/abiosoft/colima).
