### ISSUE TITLE
[Question] Removing Linux Support post-install

### ISSUE THREAD

**Issue by CanisHelix** [slonopotamus/stevedore#56]
If I installed Stevedore with `choco install stevedore` on Window Server 2022 Core (no Desktop Experience), but now I need to remove Linux Container support. What is the best process for this?

Simply remove WSL2?

Uninstall Stevedore and reinstall. (Or would this detect WSL2 and auto-enabled Linux?)

**Comment by slonopotamus** [comment]
1. If you're talking about Stevedore tray app, I'm not aware of Chocolatey-style ways to adjust already installed apps and would simply uninstall it and reinstall with proper flags.
2. Most important point: Stevedore doesn't install Linux containers support on Windows Server.
3. Even if it did, you could remove WSL2 Windows component using something like `Disable-WindowsOptionalFeature -FeatureName "Microsoft-Windows-Subsystem-Linux;VirtualMachinePlatform"` from a PowerShell

**Comment by slonopotamus** [comment]
Oh, wait, I forgot about LCOW thing...

**Comment by CanisHelix** [comment]
If I'm understanding properly. The following should install without Linux support, and as the service name 'docker':

```
 choco install stevedore --params="ADDLOCAL=FeatureWindowsContainers,FeatureHyperV SERVICENAME=docker /quiet"
```

It's still creating the service as Stevedore so not sure if the above is right now.

**Comment by slonopotamus** [comment]
I forgot again the difference between Chocolatey's `--install-arguments=`  and `--params`... I see that in ad3548ef9e00ee8fe15ef8e8b1cd77d9150b7791 I've changed the former to the latter after discussion in some of Discord chats. Maybe `--install-arguments=` was actually correct?

**Comment by Hvid** [comment]
Sure, I'm using the command:
`--installArgs "INSTALLDIR="C:\Program Files\Docker" ADDLOCAL=FeatureWindowsContainers SERVICENAME=docker /quiet"`

**Comment by Hvid** [comment]
```
     --ia, --installargs, --install-args, --installarguments, --install-arguments=VALUE
     InstallArguments - Install Arguments to pass to the native installer in 
       the package. Defaults to unspecified.

     --params, --parameters, --pkgparameters, --packageparameters, --package-parameters=VALUE
     PackageParameters - Parameters to pass to the package. Defaults to 
       unspecified.
```

`--installArgs` gets passed directly to the installer.

**Comment by slonopotamus** [comment]
So, https://github.com/slonopotamus/stevedore/commit/ad3548ef9e00ee8fe15ef8e8b1cd77d9150b7791 was wrong and needs to be reverted?
