### ISSUE TITLE
How to run windows containers?

### ISSUE THREAD

**Issue by mwmaxr** [slonopotamus/stevedore#57]
I installed stevedore using `choco install stevedore` on Win10. Running linux containers works well. However, I couldn't manage to run windows containers. The error message shows:

> image operating system "windows" cannot be used on this platform

How can I change the OSType to windows? In Docker Desktop there seems to be the option `"C:\Program Files\Docker\Docker\DockerCli.exe" -SwitchDaemon` via command line. Is there a similar option in stevedore?

**Comment by slonopotamus** [comment]
Just exit tray icon.

**Comment by olologin** [comment]
@slonopotamus 
Is it possible to add this to documentation? Or maybe add some tip in tray menu?

**Comment by slonopotamus** [comment]
Given that Stevedore [drops](https://github.com/slonopotamus/stevedore/blob/main/README.adoc#where-linux-containers-support-is-gone) Linux containers support, tray app is also gone, so there's no more switching between types of containers.
